### DISCUSSION TITLE
Is it possible to persist data accross container restarts?

### DISCUSSION THREAD

**Discussion by johaag** [danyi1212/celery-insights#66] [Q&A] [answered]
Hello all,

First of all, I want to thank @danyi1212 for this great project! It looks very promising.

We are currently evaluating Celery Insights as a successor for Flower. With Flower, it is possible to persist the home folder of the user, which is running Flower in the container. This way, past data is present in Flower, even if the container is restarted.

Is this also possible for Celery Insights?

Edit: Flower will only persist its data, if a DB is configured. In our case this DB is stored in the home folder, hence persisting the home folder worked for us.

**Comment by johaag** [comment]
Seems like it is working in the very same way as for Flower by creating a volume and mapping it to the home folder of user `myuser` (which is the user running Celery Insights in the container).

This is how I add it to the Docker Compose file:
```yaml
services:
  celery-insights:
    image: ghcr.io/danyi1212/celery-insights:latest
    ports:
      - "8555:8555"
    environment:
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
    volumes:
      - insights_data:/home/myuser/
    networks:
      - my-net

volumes:
  insights_data:
```
